### ISSUE TITLE
Cluster names in Differential Abundance/DA Interactive Tree tabs

### ISSUE THREAD

**Issue by agnieszkalih** [DII-LIH-Luxembourg/cycadas#4]
There is certain inconsistency in nodes names in these tabs - in _Differential Abundance_, "T cells" would mean "remaining T cells", while in _DA interactive tree_, these would be total T cells.
Solution: in the _Differential Abundance_ tab, could you add "(remaining clusters)" to the name of all the nodes that have children?

**Comment by oHunewald** [comment]
done
