### ISSUE TITLE
Load data tab

### ISSUE THREAD

**Issue by agnieszkalih** [DII-LIH-Luxembourg/cycadas#7]
- create additional (next to Required & Optional) tab "demo data" and move these panels there:
![image](https://github.com/DII-LIH-Luxembourg/cycadas/assets/86408182/098536af-6051-4c80-8f4a-d446430996af)

- from the "optional" tab: remove the "Upload Annotation" panel, as it is used for the flat annotation that is not inthe tool anymore.

**Comment by oHunewald** [comment]
done.
